# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git-bro}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dmitry Maksimov"]
  s.date = %q{2010-03-23}
  s.default_executable = %q{git-bro}
  s.description = %q{Git-bro provides tools to serve your Git repositories}
  s.email = %q{dmtmax@gmail.com}
  s.executables = ["git-bro"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "bin/git-bro",
     "bin/short_help.txt",
     "git-bro.gemspec",
     "lib/git-bro.rb",
     "lib/git-bro/commands.rb",
     "lib/git-bro/commands/serve.rb",
     "lib/git-bro/process.rb",
     "lib/git-bro/repository.rb",
     "lib/git-bro/sinatra/helpers.rb",
     "rakefile.rb",
     "sinatra/app.rb",
     "sinatra/public/images/file.png",
     "sinatra/public/images/folder.png",
     "sinatra/views/application.sass",
     "sinatra/views/dir.haml",
     "sinatra/views/dir_listing.haml",
     "sinatra/views/file_content.haml",
     "sinatra/views/index.haml",
     "sinatra/views/layout.haml"
  ]
  s.homepage = %q{http://github.com/kolo/git-bro}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Serve and browse your Git repositories}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grit>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

